name: Multi-Environment Deployment with Auto-Merge to Prod

on:
  push:
    branches:
      - test
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build and Deploy to Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: To_do_app/package-lock.json

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: To_do_app

      # Step 4: Run tests (only for test branch)
      - name: Run tests
        if: github.ref_name == 'test'
        run: npm test
        working-directory: To_do_app

      # Step 5: Build the app
      - name: Build the app
        run: npm run build --verbose
        working-directory: To_do_app

      # Step 6: List dist directory for debugging
      - name: List dist directory
        run: ls -alh To_do_app/dist || echo "Dist directory not found"

  auto-merge-to-prod:
    name: Auto-Merge to Prod
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: success() && github.ref == 'refs/heads/test'

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure Git User
      - name: Configure Git User
        run: |
          git config --global user.name "kudaykiranreddy"
          git config --global user.email "kudaykiranreddy143@gmail.com"

      # Step 3: Merge Test into Prod with Automatic Conflict Resolution
      - name: Merge Test into Prod
        run: |
          git fetch origin
          git checkout prod
          git merge test --strategy-option theirs --allow-unrelated-histories --no-edit
          git push origin prod

  deploy-to-aws:
    name: Deploy React App to AWS
    runs-on: ubuntu-latest
    needs: auto-merge-to-prod
    if: success()

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install
        working-directory: To_do_app

      # Step 4: Run Build Command (if build folder does not exist)
      - name: Run Build Command (if build folder does not exist)
        run: |
          if [ ! -d "To_do_app/dist" ]; then
            npm run build --prefix To_do_app
          fi

      # Step 5: Sync to S3
      - name: Sync to S3
        run: aws s3 sync To_do_app/dist s3://uday-react --delete
