name: Multi-Environment Deployment

on:
  push:
    branches:
      - test
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: To_do_app/package-lock.json

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: To_do_app

      # Step 4: Run tests (only for test branch)
      - name: Run tests
        if: github.ref_name == 'test'
        run: npm test
        working-directory: To_do_app

      # Step 5: Build the app
      - name: Build the app
        run: npm run build --verbose
        working-directory: To_do_app

      # Step 6: List dist directory for debugging
      - name: List dist directory
        run: ls -alh To_do_app/dist || echo "Dist directory not found"

      # Step 7: Merge changes from test to prod (triggered after tests pass in test branches)
      - name: Merge changes from test to prod
        if: github.ref_name == 'test' && success()  # Merge only if the tests are successful
        run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git fetch origin
            git checkout prod
            git pull origin prod  # Ensure prod is up to date
            git merge test --no-edit --allow-unrelated-histories
            git push origin prod
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}

      # Step 8: Deploy to Netlify (Only for prod branch)
      - name: Deploy to Netlify
        if: github.ref == 'refs/heads/prod'
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: To_do_app/dist
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PROD_SITE_ID }}
