name: Test Deployment

on:
  push:
    branches:
      - test

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: To_do_app/package-lock.json

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: To_do_app

      # Step 4: Build the app
      - name: Build the app
        run: npm run build --verbose
        working-directory: To_do_app

      # Step 5: Deploy to Netlify (Test environment)
      - name: Deploy to Netlify (Test)
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: To_do_app/dist
          production-deploy: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_TEST_SITE_ID }}
          HOMEPAGE_URL: ${{ secrets.HOMEPAGE_URL }}

      # Step 6: Commit and push changes (if any)
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated commit after deployment"
          git push origin test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure the token has the right permissions

      # Step 7: Create Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: test
          title: "Merge changes from Test to Prod"
          body: |
            Changes from the test branch are ready to be merged into the prod branch.
          base: prod
          delete-branch: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure the token has the right permissions
